### ISSUE TITLE
kubernetes-dashboard low version

### ISSUE THREAD

**Issue by wenbingzhang** [cloudnativer/kube-install#22]
k8s v18 
system centos7

kubernetes-dashboard the server could not find the requested resource
<img width="1354" alt="iShot2021-11-26 17 49 33" src="https://user-images.githubusercontent.com/13162606/143561456-f2e7d848-fed2-4507-b756-720c7c1e19b8.png">

**Comment by cloudnativer** [comment]
This is caused by version mismatch. We have solved this problem in version 0.7.3.

![v073update001](https://user-images.githubusercontent.com/62274882/143600219-64ce3f01-08fe-4da5-b619-b66147c003fd.png)

**Comment by cloudnativer** [comment]
`kube-install` v0.7.3 fixes many problems and supports more practical features, such as supporting multiple CNI plug-ins, supporting multiple operating systems in the same cluster, skipping kernel upgrade, etc.

![v073update002](https://user-images.githubusercontent.com/62274882/143600512-6246ab77-dd71-46e7-b00b-1db9bd8a9b35.png)

We recommend that you use the latest version of `kube install` v0.7.3 or above.

**Comment by wenbingzhang** [comment]
The “Kubernetes-dashboard”is still not working
![image](https://user-images.githubusercontent.com/13162606/143800184-48541268-1a99-46ee-a991-e889b1dd3f3a.png)

**Comment by wenbingzhang** [comment]
Looks like a missing “Dashboard-metrics-scraper.”

**Comment by wenbingzhang** [comment]
You can add a switch to install “kubernetes-dashboard”. Because “kubernetes-dashboard”isn’t necessary.

**Comment by houseonline** [comment]
> The “Kubernetes-dashboard”is still not working
> ![image](https://user-images.githubusercontent.com/13162606/143800184-48541268-1a99-46ee-a991-e889b1dd3f3a.png)

In fact, in the new version, Dashboard is already running normally. The "Dashboard-metrics-scraper" you see is used to display the monitoring graph on the Dashboard interface, "Dashboard-metrics-scraper" is an additional plug-in, and "Dashboard-metrics-scraper" is not necessary.

**Comment by houseonline** [comment]
> can add a switch to install “kubernetes-dashboard”. Because “kubernetes-dashboard”isn’t necessary.

"Kubernetes-dashboard" is used on the web interface of "kube-install", and "kube-install" integrates the most basic "kubernetes-dashboard" by default (not including "Dashboard-metrics-scraper"), so for the time being Will not become an option. We can integrate "Dashboard-metrics-scraper" in future versions.

**Comment by houseonline** [comment]
> Looks like a missing “Dashboard-metrics-scraper.”
> 
> https://raw.githubusercontent.com/kubernetes/dashboard/v2.2.0/aio/deploy/recommended.yaml


If you need "Dashboard-metrics-scraper", you can manually add "Dashboard-metrics-scraper" on the basis of Dashboard.

You can use the following code to attach "Dashboard-metrics-scraper":

```
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: dashboard-metrics-scraper
  name: dashboard-metrics-scraper
  namespace: kubernetes-dashboard
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: dashboard-metrics-scraper
  template:
    metadata:
      labels:
        k8s-app: dashboard-metrics-scraper
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'runtime/default'
    spec:
      containers:
        - name: dashboard-metrics-scraper
          image: kubernetesui/metrics-scraper:v1.0.6
          ports:
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
          - mountPath: /tmp
            name: tmp-volume
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 1001
            runAsGroup: 2001
      serviceAccountName: kubernetes-dashboard
      nodeSelector:
        "kubernetes.io/os": linux
      # Comment the following tolerations if Dashboard must not be deployed on master
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      volumes:
        - name: tmp-volume
          emptyDir: {}
```
